# Generated by Django 5.2.4 on 2025-07-28 08:24

from django.db import migrations


def indicate_price_product(apps, schema_editor):
    OrderProducts = apps.get_model('foodcartapp', 'OrderProducts')
    RestaurantMenuItem = apps.get_model('foodcartapp', 'RestaurantMenuItem')
    db_alias = schema_editor.connection.alias

    for order_product in OrderProducts.objects.using(db_alias).all():
        try:
            order_product.price = order_product.product.price

        except RestaurantMenuItem.DoesNotExist:
            order_product.price = order_product.product.price
        order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderproducts_price_restaurantmenuitem_price'),
    ]

    operations = [
        migrations.RunPython(indicate_price_product),
    ]
