# Generated by Django 5.2.4 on 2025-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_from_manager',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий менеджера'),
        ),
    ]
