# Generated by Django 5.2.4 on 2025-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличными'), ('E', 'Электронный'), ('K', 'Катртой')], db_index=True, default='C', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
