# Generated by Django 5.2.4 on 2025-07-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан для заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('U', 'Необработанный'), ('S', 'Готовится'), ('D', 'В пути'), ('V', 'Выполнен')], db_index=True, default='U', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
