# Generated by Django 5.2.4 on 2025-07-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_address', models.CharField(max_length=255, null=True, verbose_name='Первый адрес')),
                ('first_address_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта первого адреса')),
                ('first_address_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота первого адреса')),
                ('second_address', models.CharField(max_length=255, null=True, verbose_name='Второй адрес')),
                ('second_address_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта второго адреса')),
                ('second_address_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота второго адреса')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Значение расстояния (км)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'unique_together': {('first_address', 'second_address')},
            },
        ),
    ]
