# Generated by Django 5.2.4 on 2025-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfostore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodecache',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние между адресами (км)'),
        ),
        migrations.AlterField(
            model_name='geocodecache',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
