# Generated by Django 5.2.4 on 2025-08-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfostore', '0002_alter_geocodecache_distance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeocodeCache',
            new_name='GeocodingAddresses',
        ),
    ]
